# SLES docs
https://documentation.suse.com/en-us/sles/15-SP4/html/SLES-all/:
  links: ['documentation.suse.com/en-us/sles/15-SP4/html']
  selector: 'article'
  category: 'doc'
https://documentation.suse.com/en-us/subscription/suseconnect/html/SLE-suseconnect-visibility:
  links: ['documentation.suse.com/en-us/subscription/suseconnect/html']
  selector: 'article'
  category: 'doc'
https://documentation.suse.com/en-us/container/all/html/SLES-container:
  links: ['documentation.suse.com/en-us/container/all/html']
  selector: 'article'
  category: 'doc'
https://documentation.suse.com/en-us/sle-public-cloud/all/html/public-cloud:
  links: ['documentation.suse.com/en-us/sle-public-cloud/all/html']
  selector: 'article'
  category: 'doc'
https://documentation.suse.com/suma/4.3/en/suse-manager/index.html:
  links: ['documentation.suse.com/suma/4.3/en/suse-manager']
  selector: 'article'
  category: 'doc'
https://ranchermanager.docs.rancher.com/getting-started/overview:
  links: ['ranchermanager.docs.rancher.com']
  selector: 'article'
  category: 'doc'
https://docs.harvesterhci.io/v1.1/install/requirements:
  links: ['docs.harvesterhci.io/v1.1']
  selector: 'article'
  category: 'doc'
https://open-docs.neuvector.com/basics/overview:
  links: ['open-docs.neuvector.com']
  selector: '#body'
  category: 'doc'
# SUSE Blog
https://www.suse.com/c/blog:
  links: ['suse.com/c']
  selector: 'section.main'
  category: 'blog'
# Product Lifecycle
https://www.suse.com/lifecycle:
  links: ['suse.com/lifecycle']
  selector: '.lifecycle-page'
  category: 'web'
# Release Notes:
https://www.suse.com/releasenotes/index.html:
  links: ['suse.com/releasenotes']
  selector: '.article'
  category: 'web'
# SUSE Knowledge base
https://www.suse.com/support/kb: # TODO: Only paginates latest 300 articles...
  links: ['suse.com/support\/kb']
  selector: '#content'
  category: 'kb'
# Man pages, crawl in iterations, else the crawler has too many links
https://manpages.opensuse.org/Tumbleweed/index.html:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[0-9A-Z]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#1:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[a-c]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#2:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[d-f]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#3:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[g-j]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#4:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[k-m]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#5:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[n-p]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#6:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[q-s]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#7:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[t-v]']
  selector: '.mandoc'
  category: 'manpages'
https://manpages.opensuse.org/Tumbleweed/index.html#8:
  links: ['Tumbleweed/index.html', 'manpages.opensuse.org/Tumbleweed/[w-z]']
  selector: '.mandoc'
  category: 'manpages'
